### PR TITLE
Add example of using new experimental SDK package to call OpenAI from backend

### PR DESCRIPTION
**Pull request by sd2k**
This uses the `llmclient` module in the grafana-llm-app repository to make simple requests to OpenAI from a backend plugin.

---

This can be tested by building the backend with `mage -v`, starting the docker-compose services, configuring the plugin with a Grafana API key at http://localhost:3000/plugins/grafana-llmexamples-app, and running this from
a terminal:

```bash
$ curl -X POST localhost:3000/api/plugins/grafana-llmexamples-app/resources/openai -d '{"message": "hello"}'
```

[branch]: https://github.com/grafana/grafana-plugin-sdk-go/compare/experimental-llm-helpers?expand=1

### CODE REVIEW

**Review by csmarchbanks — COMMENTED** [review]
This seems fine, but yeah I was also thinking about where the best place for these to live is. If we want to support arbitrary backends calling grafana-llm-app I wonder if we should just put the helper functions in a separate package inside grafana-llm-app which could then be used here or elsewhere? I would not love having to import this many dependencies just to add an llm feature.

**Comment by sd2k** [comment]
Agreed, it feels wrong to be importing this plugin SDK just to call the LLM app plugin, not to mention the enormous dependency chain.

**Review by csmarchbanks — COMMENTED** [review]
I have mixed thoughts on this... do we expect plugin backends to be calling the llm plugin commonly instead of frontend components? I would be tempted to have a regular go example in the godoc and call it good.

It is nice to see how to store an api key though I guess...

**Comment by sd2k** [comment]
I think there's still value to having an example _somewhere_, even if it's just to let people know that we do have a backend client. I'm basing that off of the fact that I've discovered a ton of new things were possible from https://github.com/grafana/grafana-plugin-examples/ recently!

**Review by csmarchbanks — APPROVED** [review]
Discoverability of the client is a good point, happy with this then.

**Pull request merged**
